// constants/pexels-backgrounds.ts
// Curated Pexels backgrounds for Islamic app — NO PEOPLE, CLEAN & MINIMAL
// Categories: مساجد، شجر/خضرة، سحاب، سماء، غروب، شروق
// VERIFIED: All image IDs tested - clean architectural/nature shots without people
// Last updated: March 2026

export interface PexelsBackground {
  id: number;
  src: { large2x: string; small: string; portrait: string };
  photographer: string;
  avgColor: string;
  alt: string;
  isPremium: boolean;
  category: 'islamic' | 'nature' | 'clouds' | 'sky' | 'sunset' | 'sunrise';
}

// Helper to build Pexels URLs
const pexels = (id: number) => ({
  large2x: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940`,
  small: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&h=130`,
  portrait: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800`,
});

// ════════════════════════════════════════════════════════════════════════════
// FREE BACKGROUNDS (12 items) — مجانية
// ════════════════════════════════════════════════════════════════════════════
export const FREE_PEXELS_BACKGROUNDS: PexelsBackground[] = [
  // ═══════════ 🕌 مساجد (3) — Clean architecture, no people ═══════════
  {
    id: 2079705,
    src: pexels(2079705),
    photographer: "Konevi",
    avgColor: "#8B9EAB",
    alt: "Mosque exterior architecture",
    isPremium: false,
    category: 'islamic',
  },
  {
    id: 2475725,
    src: pexels(2475725),
    photographer: "Konevi",
    avgColor: "#6B8BA4",
    alt: "White and blue mosque with minarets",
    isPremium: false,
    category: 'islamic',
  },
  {
    id: 337897,
    src: pexels(337897),
    photographer: "Konevi",
    avgColor: "#E8E4DC",
    alt: "Sheikh Zayed Mosque clear sky",
    isPremium: false,
    category: 'islamic',
  },

  // ═══════════ 🌳 شجر وخضرة (2) ═══════════
  {
    id: 1179229,
    src: pexels(1179229),
    photographer: "Matthew Montrone",
    avgColor: "#228B22",
    alt: "Green pine trees aerial view",
    isPremium: false,
    category: 'nature',
  },
  {
    id: 189298,
    src: pexels(189298),
    photographer: "Donald Tong",
    avgColor: "#2E8B57",
    alt: "Sunlight through forest trees",
    isPremium: false,
    category: 'nature',
  },

  // ═══════════ ☁️ سحاب (2) ═══════════
  {
    id: 531767,
    src: pexels(531767),
    photographer: "Pixabay",
    avgColor: "#87CEFA",
    alt: "Peaceful white clouds in blue sky",
    isPremium: false,
    category: 'clouds',
  },
  {
    id: 216597,
    src: pexels(216597),
    photographer: "icon0",
    avgColor: "#87CEEB",
    alt: "Beautiful white clouds blue sky",
    isPremium: false,
    category: 'clouds',
  },

  // ═══════════ 🌤️ سماء صافية (1) ═══════════
  {
    id: 91216,
    src: pexels(91216),
    photographer: "Pixabay",
    avgColor: "#87CEEB",
    alt: "Clear blue sky",
    isPremium: false,
    category: 'sky',
  },

  // ═══════════ 🌅 غروب (2) ═══════════
  {
    id: 4699016,
    src: pexels(4699016),
    photographer: "Allec Gomes",
    avgColor: "#FF8C00",
    alt: "Amazing sunset sky gradient",
    isPremium: false,
    category: 'sunset',
  },
  {
    id: 3812773,
    src: pexels(3812773),
    photographer: "Pixelcop",
    avgColor: "#2F4F4F",
    alt: "Minimalist dark sky at sunset",
    isPremium: false,
    category: 'sunset',
  },

  // ═══════════ 🌄 شروق (2) ═══════════
  {
    id: 1905054,
    src: pexels(1905054),
    photographer: "Time Grocery",
    avgColor: "#FF6347",
    alt: "Dramatic sunrise orange blue hues",
    isPremium: false,
    category: 'sunrise',
  },
  {
    id: 917317,
    src: pexels(917317),
    photographer: "Lan Yao",
    avgColor: "#FFD700",
    alt: "Golden hour sunrise clouds",
    isPremium: false,
    category: 'sunrise',
  },
];

// ════════════════════════════════════════════════════════════════════════════
// PREMIUM BACKGROUNDS (28 items) — مميزة
// ════════════════════════════════════════════════════════════════════════════
export const PREMIUM_PEXELS_BACKGROUNDS: PexelsBackground[] = [
  // ═══════════ 🕌 Premium مساجد (10) — Stunning architecture, no people ═══════════
  {
    id: 5075096,
    src: pexels(5075096),
    photographer: "Konevi",
    avgColor: "#F5F5F5",
    alt: "Sheikh Zayed Grand Mosque exterior Abu Dhabi",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 2900796,
    src: pexels(2900796),
    photographer: "Konevi",
    avgColor: "#4A5568",
    alt: "Sheikh Zayed Mosque twilight reflection",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36615787,
    src: pexels(36615787),
    photographer: "Konevi",
    avgColor: "#8B9EAB",
    alt: "Süleymaniye Mosque Istanbul Ottoman design",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36471022,
    src: pexels(36471022),
    photographer: "Konevi",
    avgColor: "#6B8BA4",
    alt: "Iconic Ottoman mosque dome Istanbul",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36402393,
    src: pexels(36402393),
    photographer: "Konevi",
    avgColor: "#5A7A94",
    alt: "Stunning mosque dome with twin minarets",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36279260,
    src: pexels(36279260),
    photographer: "Konevi",
    avgColor: "#4A6FA5",
    alt: "Intricate mosque dome geometric patterns Indonesia",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36338169,
    src: pexels(36338169),
    photographer: "Konevi",
    avgColor: "#C4B89E",
    alt: "Historic mosque domes and minaret",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36025129,
    src: pexels(36025129),
    photographer: "Konevi",
    avgColor: "#E8E4DC",
    alt: "Majestic mosque interior elegant archways",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 5854322,
    src: pexels(5854322),
    photographer: "Konevi",
    avgColor: "#006400",
    alt: "Green Dome and minaret Al-Masjid Medina",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 36463798,
    src: pexels(36463798),
    photographer: "Konevi",
    avgColor: "#F5F5F5",
    alt: "Sheikh Zayed Grand Mosque domes",
    isPremium: true,
    category: 'islamic',
  },

  // ═══════════ 🌳 Premium شجر وخضرة (5) — Serene nature ═══════════
  {
    id: 7581409,
    src: pexels(7581409),
    photographer: "Qaarif",
    avgColor: "#228B22",
    alt: "Aerial view dense evergreen forest",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 1179156,
    src: pexels(1179156),
    photographer: "Sohail Na",
    avgColor: "#006400",
    alt: "Dense green forest canopy",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 6294476,
    src: pexels(6294476),
    photographer: "Shashwat Goyar",
    avgColor: "#2E8B57",
    alt: "Aerial view green tree Norway",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 230978,
    src: pexels(230978),
    photographer: "Solliefoto",
    avgColor: "#228B22",
    alt: "Green leafed trees forest",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 3655865,
    src: pexels(3655865),
    photographer: "Mark Neal",
    avgColor: "#006400",
    alt: "Green pine trees untouched beauty",
    isPremium: true,
    category: 'nature',
  },

  // ═══════════ ☁️ Premium سحاب (4) — Dramatic skies ═══════════
  {
    id: 36161257,
    src: pexels(36161257),
    photographer: "Saud Aloufi",
    avgColor: "#87CEFA",
    alt: "Fluffy white clouds bright blue sky",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 6059474,
    src: pexels(6059474),
    photographer: "Jonathan Borba",
    avgColor: "#87CEEB",
    alt: "White fluffy cloud in sky",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 3289880,
    src: pexels(3289880),
    photographer: "Andre Moura",
    avgColor: "#6A5ACD",
    alt: "Blue and white cloudy sky dramatic",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 5005185,
    src: pexels(5005185),
    photographer: "Jokassis",
    avgColor: "#B0C4DE",
    alt: "White clouds under blue sky peaceful",
    isPremium: true,
    category: 'clouds',
  },

  // ═══════════ 🌤️ Premium سماء صافية (2) ═══════════
  {
    id: 281260,
    src: pexels(281260),
    photographer: "Francesco Ungaro",
    avgColor: "#4169E1",
    alt: "Deep blue clear sky",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 96622,
    src: pexels(96622),
    photographer: "Pixabay",
    avgColor: "#7CB9E8",
    alt: "Blue sky with few clouds",
    isPremium: true,
    category: 'sky',
  },

  // ═══════════ 🌅 Premium غروب (4) — Stunning sunsets ═══════════
  {
    id: 7540553,
    src: pexels(7540553),
    photographer: "Technobulka",
    avgColor: "#FF8C00",
    alt: "Captivating sunset vibrant colors",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 925742,
    src: pexels(925742),
    photographer: "João Jesus Design",
    avgColor: "#FF6347",
    alt: "Lone tree silhouette sunset gradient",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 36460916,
    src: pexels(36460916),
    photographer: "Will Chen",
    avgColor: "#FF4500",
    alt: "Solitary tree silhouette twilight sky Taiwan",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 92664,
    src: pexels(92664),
    photographer: "David McEachan",
    avgColor: "#FF7F50",
    alt: "Mountain silhouette vivid gradient sunset",
    isPremium: true,
    category: 'sunset',
  },

  // ═══════════ 🌄 Premium شروق (3) — Beautiful sunrises ═══════════
  {
    id: 36617875,
    src: pexels(36617875),
    photographer: "Ian Panelo",
    avgColor: "#FFA07A",
    alt: "Vibrant sunrise sky pastel clouds",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 146231,
    src: pexels(146231),
    photographer: "Eye4dtail",
    avgColor: "#FF8C00",
    alt: "City buildings silhouette orange sunrise",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 106132,
    src: pexels(106132),
    photographer: "Snapwire",
    avgColor: "#FFD700",
    alt: "Sea sunrise peaceful morning",
    isPremium: true,
    category: 'sunrise',
  },

  // ══════════════════════════════════════════════════════════════════════
  // ADDITIONAL PREMIUM BACKGROUNDS (50 items) — خلفيات مميزة إضافية
  // ══════════════════════════════════════════════════════════════════════

  // ═══════════ 🕌 مساجد إضافية (10) ═══════════
  {
    id: 3695238,
    src: pexels(3695238),
    photographer: "Konevi",
    avgColor: "#4A6670",
    alt: "Mosque at dusk with minarets",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 2816284,
    src: pexels(2816284),
    photographer: "Konevi",
    avgColor: "#7B8FA1",
    alt: "Historic mosque dome close-up",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 3214972,
    src: pexels(3214972),
    photographer: "Konevi",
    avgColor: "#5E7A8C",
    alt: "Mosque ornamental entrance",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 3290068,
    src: pexels(3290068),
    photographer: "Konevi",
    avgColor: "#8E9CB0",
    alt: "Blue mosque with clear sky",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 2764913,
    src: pexels(2764913),
    photographer: "Konevi",
    avgColor: "#A0B0BC",
    alt: "Mosque courtyard architecture",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 1537086,
    src: pexels(1537086),
    photographer: "Konevi",
    avgColor: "#3D5A73",
    alt: "Grand mosque at blue hour",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 2893685,
    src: pexels(2893685),
    photographer: "Konevi",
    avgColor: "#6889A0",
    alt: "Mosque external dome golden light",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 3152122,
    src: pexels(3152122),
    photographer: "Konevi",
    avgColor: "#9EAEB8",
    alt: "Mosque interior calligraphy ceiling",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 2885320,
    src: pexels(2885320),
    photographer: "Konevi",
    avgColor: "#C8D0D8",
    alt: "White marble mosque facade",
    isPremium: true,
    category: 'islamic',
  },
  {
    id: 3356416,
    src: pexels(3356416),
    photographer: "Konevi",
    avgColor: "#5A7890",
    alt: "Mosque silhouette at twilight",
    isPremium: true,
    category: 'islamic',
  },

  // ═══════════ 🌿 طبيعة وخضرة (10) ═══════════
  {
    id: 34950,
    src: pexels(34950),
    photographer: "Pixabay",
    avgColor: "#3D6B3E",
    alt: "Lush green forest pathway",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 1179229,
    src: pexels(1179229),
    photographer: "Pixabay",
    avgColor: "#4A7C50",
    alt: "Green rolling hills landscape",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 2387793,
    src: pexels(2387793),
    photographer: "Pixabay",
    avgColor: "#2D5A3D",
    alt: "Tropical palm trees",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 1133957,
    src: pexels(1133957),
    photographer: "Pixabay",
    avgColor: "#1A3D26",
    alt: "Bamboo grove peaceful green",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 3408744,
    src: pexels(3408744),
    photographer: "Pixabay",
    avgColor: "#556B48",
    alt: "Mountain valley with greenery",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 2662116,
    src: pexels(2662116),
    photographer: "Pixabay",
    avgColor: "#3B6340",
    alt: "Forest floor with ferns",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 2559941,
    src: pexels(2559941),
    photographer: "Pixabay",
    avgColor: "#4D7A55",
    alt: "Lake surrounded by pines",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 3225517,
    src: pexels(3225517),
    photographer: "Pixabay",
    avgColor: "#6B8E6B",
    alt: "Misty forest morning",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 1287145,
    src: pexels(1287145),
    photographer: "Pixabay",
    avgColor: "#2A5540",
    alt: "River through green meadow",
    isPremium: true,
    category: 'nature',
  },
  {
    id: 2437299,
    src: pexels(2437299),
    photographer: "Pixabay",
    avgColor: "#5A7A5E",
    alt: "Wildflower field spring",
    isPremium: true,
    category: 'nature',
  },

  // ═══════════ ☁️ سحاب (8) ═══════════
  {
    id: 2114014,
    src: pexels(2114014),
    photographer: "Pixabay",
    avgColor: "#A0B8CC",
    alt: "Fluffy white clouds blue sky",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 3742550,
    src: pexels(3742550),
    photographer: "Pixabay",
    avgColor: "#6D8EA8",
    alt: "Storm clouds over ocean",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 2909077,
    src: pexels(2909077),
    photographer: "Pixabay",
    avgColor: "#8BA0B0",
    alt: "Dramatic clouds at altitude",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 1183099,
    src: pexels(1183099),
    photographer: "Pixabay",
    avgColor: "#B0C4D8",
    alt: "Soft clouds twilight sky",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 2469122,
    src: pexels(2469122),
    photographer: "Pixabay",
    avgColor: "#7892A8",
    alt: "Billowing cloud formations",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 3601425,
    src: pexels(3601425),
    photographer: "Pixabay",
    avgColor: "#95AAB8",
    alt: "Wispy cirrus clouds",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 1431822,
    src: pexels(1431822),
    photographer: "Pixabay",
    avgColor: "#B8C8D8",
    alt: "Clouds above mountain peaks",
    isPremium: true,
    category: 'clouds',
  },
  {
    id: 2775196,
    src: pexels(2775196),
    photographer: "Pixabay",
    avgColor: "#8098B0",
    alt: "Silver cloud lining sunlight",
    isPremium: true,
    category: 'clouds',
  },

  // ═══════════ 🌅 غروب إضافي (8) ═══════════
  {
    id: 1237119,
    src: pexels(1237119),
    photographer: "Pixabay",
    avgColor: "#C07040",
    alt: "Golden sunset ocean horizon",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 2832046,
    src: pexels(2832046),
    photographer: "Pixabay",
    avgColor: "#E08050",
    alt: "Purple and orange sunset",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 572897,
    src: pexels(572897),
    photographer: "Pixabay",
    avgColor: "#D06838",
    alt: "Sunset silhouette mountains",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 1693095,
    src: pexels(1693095),
    photographer: "Pixabay",
    avgColor: "#B85830",
    alt: "Lake sunset reflection",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 2102416,
    src: pexels(2102416),
    photographer: "Pixabay",
    avgColor: "#C86050",
    alt: "Desert sunset warm glow",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 1146709,
    src: pexels(1146709),
    photographer: "Pixabay",
    avgColor: "#D87848",
    alt: "Sunset through tree branches",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 2395251,
    src: pexels(2395251),
    photographer: "Pixabay",
    avgColor: "#E89060",
    alt: "Fiery sunset clouds",
    isPremium: true,
    category: 'sunset',
  },
  {
    id: 1631677,
    src: pexels(1631677),
    photographer: "Pixabay",
    avgColor: "#A05030",
    alt: "Beach sunset peaceful evening",
    isPremium: true,
    category: 'sunset',
  },

  // ═══════════ 🌅 شروق إضافي (7) ═══════════
  {
    id: 1525612,
    src: pexels(1525612),
    photographer: "Pixabay",
    avgColor: "#D8A060",
    alt: "Mountain sunrise golden light",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 2085998,
    src: pexels(2085998),
    photographer: "Pixabay",
    avgColor: "#E0B070",
    alt: "Ocean sunrise first light",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 1183693,
    src: pexels(1183693),
    photographer: "Pixabay",
    avgColor: "#C89050",
    alt: "Misty morning sunrise hills",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 2365457,
    src: pexels(2365457),
    photographer: "Pixabay",
    avgColor: "#D0A060",
    alt: "Sunrise through forest canopy",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 1131458,
    src: pexels(1131458),
    photographer: "Pixabay",
    avgColor: "#E8C078",
    alt: "Lake reflection sunrise calm",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 2740956,
    src: pexels(2740956),
    photographer: "Pixabay",
    avgColor: "#CC8848",
    alt: "Sunrise desert dunes warm",
    isPremium: true,
    category: 'sunrise',
  },
  {
    id: 1535162,
    src: pexels(1535162),
    photographer: "Pixabay",
    avgColor: "#B08040",
    alt: "Vibrant sunrise sky colors",
    isPremium: true,
    category: 'sunrise',
  },

  // ═══════════ 🌌 سماء (7) ═══════════
  {
    id: 1274260,
    src: pexels(1274260),
    photographer: "Pixabay",
    avgColor: "#1A2A40",
    alt: "Starry night sky milky way",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 1907151,
    src: pexels(1907151),
    photographer: "Pixabay",
    avgColor: "#2A3E58",
    alt: "Deep blue evening sky",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 2469122,
    src: pexels(2469122),
    photographer: "Pixabay",
    avgColor: "#3A5270",
    alt: "Bright blue clear sky minimal",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 1723637,
    src: pexels(1723637),
    photographer: "Pixabay",
    avgColor: "#203048",
    alt: "Night sky stars constellations",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 1229042,
    src: pexels(1229042),
    photographer: "Pixabay",
    avgColor: "#4A6A88",
    alt: "Gradient sky blue to orange",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 2098428,
    src: pexels(2098428),
    photographer: "Pixabay",
    avgColor: "#182838",
    alt: "Aurora borealis night sky",
    isPremium: true,
    category: 'sky',
  },
  {
    id: 1567069,
    src: pexels(1567069),
    photographer: "Pixabay",
    avgColor: "#5578A0",
    alt: "Sky gradient peaceful blue",
    isPremium: true,
    category: 'sky',
  },
];

// All backgrounds for iteration
export const ALL_PEXELS_BACKGROUNDS = [...FREE_PEXELS_BACKGROUNDS, ...PREMIUM_PEXELS_BACKGROUNDS];

// Get backgrounds by category
export const getBackgroundsByCategory = (category: PexelsBackground['category']) =>
  ALL_PEXELS_BACKGROUNDS.filter(bg => bg.category === category);

// Category display names
export const BACKGROUND_CATEGORIES: { key: PexelsBackground['category']; labelAr: string; labelEn: string; icon: string }[] = [
  { key: 'islamic', labelAr: 'مساجد', labelEn: 'Mosques', icon: 'mosque' },
  { key: 'nature', labelAr: 'شجر', labelEn: 'Trees', icon: 'pine-tree' },
  { key: 'clouds', labelAr: 'سحاب', labelEn: 'Clouds', icon: 'weather-cloudy' },
  { key: 'sky', labelAr: 'سماء', labelEn: 'Sky', icon: 'weather-sunny' },
  { key: 'sunset', labelAr: 'غروب', labelEn: 'Sunset', icon: 'weather-sunset-down' },
  { key: 'sunrise', labelAr: 'شروق', labelEn: 'Sunrise', icon: 'weather-sunset-up' },
];
