/**
 * Notification Channels — إدارة قنوات الإشعارات
 *
 * ONE CHANNEL PER SOUND FILE — Android caches channel sounds at creation time
 * and they are immutable afterward. Instead of deleting/recreating channels
 * when the user changes their sound preference, we create ALL possible
 * channels upfront at app startup and simply switch which channelId we use
 * when scheduling notifications.
 *
 * Sound name rules:
 * - Filename only, lowercase, no path prefix
 * - Android raw resources: WITHOUT .mp3 extension
 * - iOS: WITH .mp3 extension
 */

import * as Notifications from 'expo-notifications';
import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { t } from '@/lib/i18n';

// Bump this whenever channel config changes (sounds, importance, etc.)
// Forces a delete+recreate of all channels on next app launch.
const CHANNELS_VERSION_KEY = 'notificationChannelsVersion';
const CURRENT_CHANNELS_VERSION = '15';

// ─── Adhan sound filename map (all files in assets/sounds/) ─────────────────
export const ADHAN_SOUND_FILES: Record<string, string> = {
  abdulbasit:       'abdulbasit.mp3',
  ajman:            'ajman.mp3',
  alaqsa:           'alaqsa.mp3',
  ali_mulla:        'ali_mulla.mp3',
  dosari:           'dosari.mp3',
  egypt:            'egypt.mp3',
  haramain:         'haramain.mp3',
  madinah:          'madinah.mp3',
  makkah:           'makkah.mp3',
  mansoor_zahrani:  'mansoor_zahrani.mp3',
  mishary:          'mishary.mp3',
  naqshbandi:       'naqshbandi.mp3',
  sharif:           'sharif.mp3',
  silent:           'silent.mp3',
  sudais:           'sudais.mp3',
};

// ─── iOS short adhan files (<30s, WAV) for local notification sound limit ────
// iOS enforces a strict 30-second limit on local notification sounds.
// These are 28-second trimmed WAV versions of each adhan (generated by
// scripts/trim-adhan-ios.sh). Android continues to use the full-length
// MP3 files via channel sound configuration.
export const IOS_ADHAN_SHORT_FILES: Record<string, string> = {
  abdulbasit:       'abdulbasit_short.wav',
  ajman:            'ajman_short.wav',
  alaqsa:           'alaqsa_short.wav',
  ali_mulla:        'ali_mulla_short.wav',
  dosari:           'dosari_short.wav',
  egypt:            'egypt_short.wav',
  haramain:         'haramain_short.wav',
  madinah:          'madinah_short.wav',
  makkah:           'makkah_short.wav',
  mansoor_zahrani:  'mansoor_zahrani_short.wav',
  mishary:          'mishary_short.wav',
  naqshbandi:       'naqshbandi_short.wav',
  sharif:           'sharif_short.wav',
  sudais:           'sudais_short.wav',
};

// ─── Notification/reminder sound filename map (all files in assets/sounds/) ──
export const NOTIFICATION_SOUND_FILES: Record<string, string> = {
  alhamdulillah:    'alhamdulillah.mp3',
  evening_adhkar:   'evening_adhkar.mp3',
  general_reminder: 'general_reminder.mp3',
  istighfar:        'istighfar.mp3',
  morning_adhkar:   'morning_adhkar.mp3',
  salawat:          'salawat.mp3',
  subhanallah:      'subhanallah.mp3',
  tasbih:           'tasbih.mp3',
};

/**
 * Resolve a sound key to the platform-correct filename.
 * Android raw resources are referenced WITHOUT extension.
 * iOS uses the full filename WITH extension.
 */
export function resolveSoundFile(filename: string): string {
  if (Platform.OS === 'android') {
    return filename.replace(/\.mp3$/, '');
  }
  return filename;
}

// ─── Channel ID Helpers (synchronous — pure map lookups) ─────────────────────

/**
 * Get the Android notification channel ID for an adhan sound.
 * Returns a channel ID like 'adhan_makkah'. All channels are pre-created at startup.
 */
export function getAdhanChannelId(soundKey?: string): string {
  if (!soundKey || soundKey === 'default') return 'adhan_makkah';
  if (soundKey === 'silent') return 'silent';
  // Strip .mp3 if passed with extension
  const key = soundKey.replace(/\.mp3$/, '');
  if (ADHAN_SOUND_FILES[key]) return `adhan_${key}`;
  return 'adhan_makkah'; // fallback
}

/**
 * Get the Android notification channel ID for a reminder sound.
 * Returns a channel ID like 'reminder_salawat'. All channels are pre-created at startup.
 */
export function getReminderChannelId(soundKey?: string): string {
  if (!soundKey || soundKey === 'default') return 'reminder_general_reminder';
  if (soundKey === 'silent') return 'silent';
  // Strip .mp3 if passed with extension
  const key = soundKey.replace(/\.mp3$/, '');
  if (NOTIFICATION_SOUND_FILES[key]) return `reminder_${key}`;
  // Some callers pass adhan sound keys for reminders
  if (ADHAN_SOUND_FILES[key]) return `adhan_${key}`;
  return 'reminder_general_reminder'; // fallback
}

// ─── Channel Initialization ─────────────────────────────────────────────────

/**
 * Create ALL notification channels at app startup.
 * One channel per sound file — ~27 channels total.
 *
 * Safe to call multiple times: Android ignores duplicate channel creation
 * (but also ignores sound changes on existing channels, which is WHY
 * we create one channel per sound file upfront and never delete them).
 *
 * Call this ONCE on mount, OUTSIDE of Firebase init.
 */
export async function initializeAllNotificationChannels(): Promise<void> {
  if (Platform.OS !== 'android') return;

  try {
    // Channel groups for organization in Android settings
    await Notifications.setNotificationChannelGroupAsync('prayer', {
      name: 'أوقات الصلاة',
    });
    await Notifications.setNotificationChannelGroupAsync('reminders', {
      name: 'التذكيرات والأذكار',
    });
  } catch (e) {
    console.warn('[Channels] Failed to create channel groups:', e);
  }

  // --- ADHAN CHANNELS (one per adhan sound file) ---
  for (const [key, filename] of Object.entries(ADHAN_SOUND_FILES)) {
    if (key === 'silent') continue; // handled separately
    const channelId = `adhan_${key}`;
    const soundFile = resolveSoundFile(filename);
    try {
      await Notifications.setNotificationChannelAsync(channelId, {
        name: `أذان - ${key}`,
        groupId: 'prayer',
        importance: Notifications.AndroidImportance.MAX,
        sound: soundFile,
        audioAttributes: {
          usage: Notifications.AndroidAudioUsage.ALARM,
          contentType: Notifications.AndroidAudioContentType.SONIFICATION,
          flags: {
            enforceAudibility: true,
            requestHardwareAudioVideoSynchronization: false,
          },
        },
        vibrationPattern: [0, 500, 250, 500],
        enableVibrate: true,
        lightColor: '#1B5E20',
        lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
        bypassDnd: false,
      });
    } catch (e) {
      console.warn(`[Channels] Failed to create ${channelId}:`, e);
    }
  }

  // --- REMINDER CHANNELS (one per notification sound file) ---
  for (const [key, filename] of Object.entries(NOTIFICATION_SOUND_FILES)) {
    const channelId = `reminder_${key}`;
    const soundFile = resolveSoundFile(filename);
    try {
      await Notifications.setNotificationChannelAsync(channelId, {
        name: `تذكير - ${key}`,
        groupId: 'reminders',
        importance: Notifications.AndroidImportance.HIGH,
        sound: soundFile,
        vibrationPattern: [0, 250, 250, 250],
        enableVibrate: true,
        lightColor: '#1B5E20',
      });
    } catch (e) {
      console.warn(`[Channels] Failed to create ${channelId}:`, e);
    }
  }

  // --- SILENT CHANNEL ---
  try {
    await Notifications.setNotificationChannelAsync('silent', {
      name: 'صامت',
      importance: Notifications.AndroidImportance.HIGH,
      sound: null,
      enableVibrate: false,
    });
  } catch (e) {
    console.warn('[Channels] Failed to create silent:', e);
  }

  // --- GENERAL CHANNEL (system default sound — used by app-update-checker, refresh reminders) ---
  try {
    await Notifications.setNotificationChannelAsync('general', {
      name: t('notifications.generalChannel') || 'إشعارات عامة',
      importance: Notifications.AndroidImportance.HIGH,
      sound: 'default',
      enableVibrate: true,
    });
  } catch (e) {
    console.warn('[Channels] Failed to create general:', e);
  }

  // --- DEFAULT CHANNEL (fallback) ---
  try {
    await Notifications.setNotificationChannelAsync('default', {
      name: 'الافتراضي',
      importance: Notifications.AndroidImportance.HIGH,
      sound: 'default',
      enableVibrate: true,
    });
  } catch (e) {
    console.warn('[Channels] Failed to create default:', e);
  }

  // --- PRAYER COMPLETION CHANNEL (default device sound — used for "هل صليت?" fallback & "تقبّل الله" notifications) ---
  try {
    await Notifications.setNotificationChannelAsync('completion_default', {
      name: 'إشعارات اكتمال الصلاة',
      groupId: 'reminders',
      importance: Notifications.AndroidImportance.HIGH,
      sound: 'default',
      vibrationPattern: [0, 250, 250, 250],
      enableVibrate: true,
      lightColor: '#1B5E20',
      lockscreenVisibility: Notifications.AndroidNotificationVisibility.PUBLIC,
    });
  } catch (e) {
    console.warn('[Channels] Failed to create completion_default:', e);
  }

  console.log('[Channels] All notification channels initialized successfully');
}

// ─── Version-Based Channel Reset ────────────────────────────────────────────

/**
 * Delete all cached channels if they were created by an older version.
 * Android caches channels permanently — even across app updates.
 * This ensures existing users get their channels recreated with the
 * correct sounds after we ship a fix.
 *
 * Call this BEFORE initializeAllNotificationChannels on every cold start.
 */
export async function resetChannelsIfOutdated(): Promise<void> {
  if (Platform.OS !== 'android') return;

  const savedVersion = await AsyncStorage.getItem(CHANNELS_VERSION_KEY);

  if (savedVersion !== CURRENT_CHANNELS_VERSION) {
    console.log('[Channels] Outdated channels detected, resetting...', { saved: savedVersion, current: CURRENT_CHANNELS_VERSION });

    try {
      console.log('[Channels] Getting existing channels...');
      const existingChannels = await Notifications.getNotificationChannelsAsync();
      console.log('[Channels] Found', existingChannels.length, 'existing channels');
      for (const channel of existingChannels) {
        try {
          await Notifications.deleteNotificationChannelAsync(channel.id);
          console.log('[Channels] Deleted channel:', channel.id);
        } catch (delErr) {
          console.warn('[Channels] Failed to delete channel', channel.id, delErr);
        }
      }

      // Reset battery optimization dialog flag so existing users who saw
      // the broken "Battery Title" / "Battery Body" dialog get the
      // properly translated version on this update.
      await AsyncStorage.removeItem('@battery_opt_asked');

      console.log('[Channels] Saving new version...');
      await AsyncStorage.setItem(CHANNELS_VERSION_KEY, CURRENT_CHANNELS_VERSION);

      console.log('[Channels] All old channels deleted successfully');
    } catch (resetErr) {
      console.error('[Channels] resetChannelsIfOutdated FAILED:', resetErr);
      // Save version anyway to prevent infinite retry loop
      try { await AsyncStorage.setItem(CHANNELS_VERSION_KEY, CURRENT_CHANNELS_VERSION); } catch {}
    }
  }
}
