/**
 * Unified notification sound resolution.
 *
 * Single source of truth for turning a soundType key (e.g. "salawat", "makkah")
 * into the platform-appropriate filename that expo-notifications expects.
 *
 * Extracted from notifications-manager.ts to avoid a require cycle between
 * notifications-manager.ts ↔ prayer-notifications.ts.
 */
import Constants from 'expo-constants';
import { Platform } from 'react-native';
import { getNotificationSoundValueSync } from './notification-sound-installer';
import {
  NOTIFICATION_SOUND_FILES,
  ADHAN_SOUND_FILES,
  IOS_ADHAN_SHORT_FILES,
  resolveSoundFile,
} from '@/services/notifications/channels';

// ─── Merged sound map (single source of truth from channels.ts) ──────────────
const ALL_SOUND_FILES: Record<string, string> = {
  ...NOTIFICATION_SOUND_FILES,
  ...ADHAN_SOUND_FILES,
};

/**
 * Resolve a soundType to the native sound value for notification content.
 *
 * - iOS: filename with .mp3 extension (must match app.json sounds)
 * - Android: filename WITHOUT .mp3 (raw resource name); actual sound
 *   comes from the channel, but we set content.sound as well for completeness
 * - Returns false for truly silent notifications
 *
 * Resolution: custom installed (Firebase) → bundled sound → general_reminder fallback.
 * NEVER returns 'default' in production builds — always a real bundled filename.
 * In Expo Go, returns 'default' because custom sounds aren't bundled.
 *
 * @param isAdhan  When true AND Platform.OS === 'ios', resolves to the short
 *                 (<30s) WAV version of the adhan. iOS enforces a strict
 *                 30-second limit on local notification sounds — full-length
 *                 adhan files cause the notification to be silently dropped.
 *                 Android ignores this flag and always uses the full file.
 */
const isExpoGo = Constants.appOwnership === 'expo';

export function resolveNotificationSound(soundType?: string, soundEnabled?: boolean, isAdhan?: boolean): string | false {
  if (soundEnabled === false || soundType === 'silent') {
    return false;
  }

  // Expo Go: custom sounds aren't bundled — use system sound so something plays
  if (isExpoGo) return 'default';

  // Determine the key to look up
  // 'default' or missing soundType → 'makkah' for adhan-like contexts,
  // but we resolve to 'general_reminder' for non-adhan contexts here.
  // The caller (prayer-notifications.ts) already forces 'makkah' before calling us,
  // so this fallback mainly catches edge cases from other callers.
  const key = (!soundType || soundType === 'default') ? 'general_reminder' : soundType;

  // ─── iOS Adhan: use short WAV versions (<30s) ────────────────────────────
  // Apple enforces a strict 30-second limit on local notification sounds.
  // Full-length adhan files exceed this and cause iOS to silently drop
  // the notification entirely. We route to per-reciter short WAV files
  // generated by scripts/trim-adhan-ios.sh.
  // Android always uses the full-length file via channel sound config.
  if (isAdhan && Platform.OS === 'ios') {
    const shortFile = IOS_ADHAN_SHORT_FILES[key] || IOS_ADHAN_SHORT_FILES['makkah'] || 'makkah_short.wav';
    console.log(`[resolve-notification-sound] iOS adhan: ${key} → ${shortFile}`);
    return shortFile;
  }

  // 1. Check installed custom sounds (downloaded from Firebase)
  const customSoundValue = getNotificationSoundValueSync(key);
  if (customSoundValue) {
    // iOS: validate the filename looks correct (.mp3 extension) before using it.
    // iOS silently drops the ENTIRE notification if content.sound references a
    // file that doesn't exist in Library/Sounds/. Fall through to bundled
    // sounds if the custom value looks invalid.
    if (Platform.OS === 'ios' && !customSoundValue.endsWith('.mp3')) {
      console.warn(`[resolve-notification-sound] iOS custom sound for ${key} missing .mp3 extension ("${customSoundValue}"), skipping`);
    } else {
      console.log(`[resolve-notification-sound] Using custom installed sound for ${key}: ${customSoundValue}`);
      return customSoundValue;
    }
  }

  // 2. Look up in the authoritative sound maps from channels.ts
  const file = ALL_SOUND_FILES[key];
  if (file) {
    return resolveSoundFile(file);
  }

  // 3. Unknown sound type — fall back to a real bundled file
  console.warn(`[resolve-notification-sound] Sound type '${key}' not found, falling back to general_reminder`);
  const fallbackFile = NOTIFICATION_SOUND_FILES['general_reminder'];
  if (fallbackFile) {
    return resolveSoundFile(fallbackFile);
  }

  // 4. Terminal fallback — if even general_reminder is missing (corrupted build),
  // return true so the OS plays the default system sound.
  // iOS silently drops notifications with an invalid sound string, so `true`
  // (system default) is always safer than a filename that might not exist.
  console.warn('[resolve-notification-sound] general_reminder not found in sound maps — using system default (true)');
  return true as unknown as string;
}
