// lib/widgets/registry.ts
// Single source of truth for every widget that exists in this app.
//
// Consumers:
//   - app/widget.tsx            (gallery — derives sections by category + platform)
//   - lib/widgets/snapshot.tsx  (renders each definition × size to a PNG)
//   - lib/widget-data-bridge.ts (decides which native providers to reload)
//   - lib/android-widget-task-handler.tsx (premium gating + thin shells)
//   - widgets/ios/Generated*.swift (Swift mirror, generated by scripts/generate-widget-enum.mjs)
//
// Bump WIDGET_REGISTRY_VERSION whenever you change the visual output of a widget
// (font, layout, anchor coordinates). The snapshot pipeline uses this in its hash
// to decide whether to re-render PNGs.

import type React from 'react';
import type { PreviewSize } from '@/components/widgets/previews/shared';

// Phase E: Hijri SVG height fix, Month Thuluth small wmFs/wmY tweak,
// Azkar font swap WidgetFont2 → Amiri.
// Phase H: prayer/digital previews now honor `forSnapshot` and omit live regions
// so the native overlay no longer ghosts on top of stale digits (constraint C2).
// v4: snapshot host avoids opacity:0 fringe; GlassTile hides shadow during capture.
// v5: PNGs are now transparent foregrounds (root bg + BlurView dropped during
// capture) and keyed per resolved theme — `<id>_<size>_<theme>.png`. Native
// shells paint the themed background underneath so theme changes via iOS
// Edit Widget update the entire widget without a full re-pump.
// v6: verifyAlpha() now runs on tmpUri (app sandbox) instead of App Group path
// so hashes are correctly stored and re-pump is not triggered every launch.
// v7: Thuluth/Hijri previews use larger lineHeight (fs * 1.9) + asymmetric
// paddingTop so calligraphic ascenders (alif tops, harakat) stay inside the
// GlassTile bounds. Hijri watermark + subtitle now use 'هجرياً' instead of 'هجري'/'هـ'.
// v8: Thuluth/Hijri use lineHeight: fs * 1.85 (bbox includes ascenders) WITHOUT
// adjustsFontSizeToFit (was shrinking text to invisibility on medium when bbox
// exceeded available height). No paddingTop on inner View — lineHeight provides
// the headroom internally so glyphs paint within widget bounds.
// v9: Thuluth/Month/Hijri reduce fontSize (38/56→30/46, 26/40→22/32, 20/30→18/26)
// + add paddingTop (22/28) + lineHeight 1.5x + re-enable adjustsFontSizeToFit
// (minScale 0.7). Smaller font means smaller diacritics, paddingTop pushes text
// down inside widget so calligraphic ascenders fit within GlassTile bounds.
// v10: Thuluth/Hijri/Month restore prominent fontSize (34/52, 26/38, 22/32) +
// remove explicit lineHeight (let DecoTypeThuluth font's natural metrics drive)
// + add includeFontPadding:false (Android cleaner alignment) + larger paddingTop
// (32/42 Thuluth, 24/32 MonthSimple, 26/36 Hijri). Auto-fit min 0.75. This
// matches the bold target Thuluth styling without clipping ascenders.
// v11: Move ascender headroom INSIDE the Text element via paddingTop:fs*0.55.
// This shifts glyphs down within the text bbox so calligraphic diacritics paint
// in dedicated padding space above. Parent View paddingTop reduced (14/18) since
// the headroom is now in the Text. Watermark also gets paddingTop:wmFs*0.4.
// v12: Apply the same paddingTop:fs*0.55 ascender-headroom fix to the remaining
// calligraphic watermarks — VersePreview "آيـة اليـوم" + PrayerLarge "الصــلاة" —
// so all RN Text elements using widgetFont/widgetFontL paint diacritics within
// bounds. SVG watermarks are unaffected (explicit baseline positioning).
// v13: Hijri watermark "هجرياً" was clipped horizontally — only "ه" visible
// because calligraphic font at fs=130 was wider than widget. Reduced watermarkFs
// (70/130 → 44/72) + added adjustsFontSizeToFit (min 0.5) so the FULL word
// renders within widget width. Inset by 8px both sides to give visual breathing.
// v14: Hijri watermark + subtitle now read 'هجري' (no tanween). Watermark
// paddingTop bumped 0.5→0.55*fs (matches Thuluth main text) so calligraphic
// ascenders fit inside the bbox. marginTop adjusted in tandem to keep center.
// v15: Added 23 variant-specific Android receivers (RoohDaySimpleSmall, etc.)
// so each widget appears as its own tile in the Android widget picker — was
// previously just 3 generic shells (RoohSmall/Medium/Large).
// v16: Home-screen parity: iOS and Android now expose the same registry set
// (Month Elegant on Android, Daily Dhikr on iOS), plus Android keyguard provider
// names for the same lock-screen content shipped by WidgetKit.
// v17: Android snapshots include the complete rounded preview tile and native
// refresh waits for the active snapshot before rendering.
// v18: Android launcher widget picker uses real per-widget thumbnails instead
// of the generic app-logo preview, with premium thumbnails marked consistently.
// v19: iOS target uses a compiled registry fallback and active snapshot writes
// are awaited before WidgetKit reloads, so Edit Widget / in-app setting changes
// cannot fall back to the default Day Simple tile.
export const WIDGET_REGISTRY_VERSION = 25; // per-widget prayer countdown overlay anchors

export type WidgetCategory = 'date' | 'prayer' | 'quran' | 'azkar' | 'hijri';
export type WidgetPlatform = 'ios' | 'android';
export type WidgetTextColorRole = 'text' | 'muted';
export type WidgetTextAlign = 'left' | 'center' | 'right';

/**
 * Per-size hot-zone metadata for the live native overlay (countdown, time-of-day,
 * etc.). Coordinates are in **logical points** within the widget's rendered size
 * as returned by `getSizeDims(size)` (see components/widgets/previews/shared.ts).
 *
 * The snapshot renderer leaves this region transparent (see C2) so the live
 * native Text drawn at the same coordinates doesn't ghost over stale digits.
 */
export interface WidgetOverlayAnchor {
  /** Centre x of the overlay text (points within widget). */
  x: number;
  /** Baseline y of the overlay text (points within widget). */
  y: number;
  fontSize: number;
  /** PostScript family name. Must be present in both iOS extension and Android widget asset bundle. */
  fontFamily: string;
  align: WidgetTextAlign;
  color: WidgetTextColorRole;
  /** Width of the transparent rectangle the snapshot leaves blank. Defaults to fontSize × 8 if omitted. */
  clearWidth?: number;
  /** Height of the transparent rectangle. Defaults to fontSize × 1.4 if omitted. */
  clearHeight?: number;
}

/**
 * What kind of live data drives the overlay text. Determines how the iOS / Android
 * shell computes the string to draw on top of the snapshot.
 *
 *   - 'prayerCountdown'  → "بعد X س Y د" / "in Xh Ym" — refreshes every minute
 *   - 'prayerNextTime'   → "04:14"        — refreshes every 5 min
 *   - 'currentTime'      → "10:38"        — refreshes every minute
 *
 * Snapshot omits the text when this is set (see C2).
 */
export type WidgetOverlayKind =
  | 'prayerCountdown'
  | 'prayerNextTime'
  | 'currentTime';

export interface WidgetDefinition<TPreviewProps = { size: PreviewSize; language?: 'ar' | 'en' }> {
  /** Stable id used in PNG filenames, intent enums, and analytics. snake-case-free, kebab-allowed. */
  id: string;
  category: WidgetCategory;
  titleAr: string;
  titleEn: string;
  /** Which sizes this widget renders. Drives snapshot output count. */
  sizes: PreviewSize[];
  /** Platforms where this widget is shipped end-to-end. */
  platforms: WidgetPlatform[];
  isPremium: boolean;
  /**
   * When set, only these sizes require an active subscription. When omitted and
   * `isPremium` is true, every size is premium. Use for variants like Day Thuluth
   * (small free / medium gated).
   */
  premiumSizes?: PreviewSize[];
  /** Force the preview / snapshot to render in a specific language regardless of app locale. */
  forcedLanguage?: 'ar' | 'en';
  /** React component that renders the preview tile (also used by snapshot renderer). */
  Preview: React.FC<TPreviewProps>;
  /** Set when the widget includes a value that must update faster than the snapshot cadence. */
  overlay?: {
    kind: WidgetOverlayKind;
    anchors: Partial<Record<PreviewSize, WidgetOverlayAnchor>>;
  };
  /**
   * When true on iOS, the widget extension renders this kind via baked
   * per-state PNGs in `widgets/ios/Assets.xcassets/PrayerStatic/` plus a
   * native numeric overlay (`PrayerStaticOverlay.swift`). The snapshot pump
   * skips capturing runtime PNGs for this kind on iOS. Android continues to
   * consume runtime snapshots until it adopts the same architecture.
   */
  iosStaticPng?: boolean;
  /** Deep link opened when the user taps the widget. */
  deepLink: string;
  /** Optional iOS WidgetKit App Intent enum raw value. Codegen will use definition.id when omitted. */
  iosKind?: string;
  /**
   * Grouped Android provider name. Multiple variants share a provider; the user
   * picks the variant in the configuration activity.
   * Format: `Rooh<Category><Size>`, e.g. `RoohDateSmall`.
   */
  androidProvider?: string;
  /**
   * Legacy Android provider name (one of the 14 originally registered widgets).
   * Kept for backward compatibility with existing home-screen placements. See C3.
   * When present, the legacy provider's renderer delegates to the new pipeline
   * for this `id`.
   */
  legacyAndroidProvider?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Lazy preview lookup — keeps the registry import cycle-free. Components are
// resolved on first access from a single barrel module.
// ─────────────────────────────────────────────────────────────────────────────

import * as Previews from '@/components/widgets/previews';

const P = Previews as Record<string, React.FC<any>>;

// ─────────────────────────────────────────────────────────────────────────────
// Registry — every widget defined exactly once.
// ─────────────────────────────────────────────────────────────────────────────

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // ── Date / time ────────────────────────────────────────────────────────────
  {
    id: 'daySimple',
    category: 'date',
    titleAr: 'اليوم',
    titleEn: 'Day Simple',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: false,
    Preview: P.DaySimplePreview,
    deepLink: 'rooh-almuslim://hijri',
    androidProvider: 'RoohDateSmall',
    legacyAndroidProvider: 'RoohSmall',
  },
  {
    id: 'dayThuluth',
    category: 'date',
    titleAr: 'اليوم - ثلث',
    titleEn: 'Day Thuluth',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: false,
    premiumSizes: ['medium'],
    forcedLanguage: 'ar',
    Preview: P.DayThuluthPreview,
    deepLink: 'rooh-almuslim://hijri',
    androidProvider: 'RoohDateSmall',
  },
  {
    id: 'dayDigital',
    category: 'date',
    titleAr: 'اليوم - رقمي',
    titleEn: 'Day Digital',
    sizes: ['small'],
    platforms: ['ios', 'android'],
    isPremium: false,
    Preview: P.DayDigitalPreview,
    deepLink: 'rooh-almuslim://hijri',
    overlay: {
      kind: 'currentTime',
      anchors: {
        small: { x: 78, y: 70, fontSize: 44, fontFamily: 'Rubik-Bold', align: 'center', color: 'text', clearWidth: 130, clearHeight: 56 },
      },
    },
    androidProvider: 'RoohDateSmall',
  },
  {
    id: 'monthSimple',
    category: 'date',
    titleAr: 'الشهر',
    titleEn: 'Month Simple',
    sizes: ['small'],
    platforms: ['ios', 'android'],
    isPremium: false,
    Preview: P.MonthSimplePreview,
    deepLink: 'rooh-almuslim://hijri',
    androidProvider: 'RoohDateSmall',
  },
  {
    id: 'monthThuluth',
    category: 'date',
    titleAr: 'الشهر - ثلث',
    titleEn: 'Month Thuluth',
    sizes: ['medium'],
    platforms: ['ios', 'android'],
    isPremium: true,
    forcedLanguage: 'ar',
    Preview: P.MonthThuluthPreview,
    deepLink: 'rooh-almuslim://hijri',
    androidProvider: 'RoohDateMedium',
  },
  // ── Prayer ─────────────────────────────────────────────────────────────────
  {
    id: 'prayerSingle',
    category: 'prayer',
    titleAr: 'الصلاة القادمة',
    titleEn: 'Prayer Simple',
    sizes: ['small'],
    platforms: ['ios', 'android'],
    isPremium: false,
    iosStaticPng: true,
    Preview: P.PrayerSimplePreview,
    deepLink: 'rooh-almuslim://prayer',
    overlay: {
      kind: 'prayerCountdown',
      anchors: {
        small: { x: 78, y: 130, fontSize: 10, fontFamily: 'Rubik-Medium', align: 'center', color: 'muted', clearWidth: 140, clearHeight: 14 },
      },
    },
    androidProvider: 'RoohPrayerSmall',
    legacyAndroidProvider: 'PrayerTimesSmall',
  },
  {
    id: 'prayerTable',
    category: 'prayer',
    titleAr: 'جدول الصلاة',
    titleEn: 'Prayer Table',
    sizes: ['small', 'medium', 'large'],
    platforms: ['ios', 'android'],
    isPremium: false,
    iosStaticPng: true,
    Preview: P.PrayerTablePreview,
    deepLink: 'rooh-almuslim://prayer',
    overlay: {
      kind: 'prayerCountdown',
      anchors: {
        small: { x: 44, y: 24, fontSize: 9, fontFamily: 'Rubik-Medium', align: 'left', color: 'muted', clearWidth: 82, clearHeight: 12 },
        medium: { x: 246, y: 130, fontSize: 9, fontFamily: 'Rubik-Medium', align: 'center', color: 'muted', clearWidth: 112, clearHeight: 12 },
        large: { x: 246, y: 126, fontSize: 12, fontFamily: 'Rubik-Medium', align: 'center', color: 'muted', clearWidth: 180, clearHeight: 18 },
      },
    },
    androidProvider: 'RoohPrayerMedium',
    legacyAndroidProvider: 'PrayerTimesLarge',
  },
  {
    id: 'prayerNextPrevious',
    category: 'prayer',
    titleAr: 'الصلاة السابقة والقادمة',
    titleEn: 'Next & Previous',
    sizes: ['medium'],
    platforms: ['ios', 'android'],
    isPremium: false,
    iosStaticPng: true,
    Preview: P.PrayerNextPrevPreview,
    deepLink: 'rooh-almuslim://prayer',
    overlay: {
      kind: 'prayerCountdown',
      anchors: {
        medium: { x: 91, y: 126, fontSize: 9, fontFamily: 'Rubik-Medium', align: 'center', color: 'muted', clearWidth: 120, clearHeight: 12 },
      },
    },
    androidProvider: 'RoohPrayerMedium',
  },

  // ── Quran ──────────────────────────────────────────────────────────────────
  {
    id: 'verseOfDay',
    category: 'quran',
    titleAr: 'آية اليوم',
    titleEn: 'Verse of Day',
    sizes: ['small', 'medium', 'large'],
    platforms: ['ios', 'android'],
    isPremium: true,
    Preview: P.VersePreview,
    deepLink: 'rooh-almuslim://daily-ayah',
    androidProvider: 'RoohQuranSmall',
    legacyAndroidProvider: 'DailyVerseSmall',
  },

  // ── Azkar ──────────────────────────────────────────────────────────────────
  {
    id: 'azkarMorning',
    category: 'azkar',
    titleAr: 'أذكار الصباح',
    titleEn: 'Morning Adhkar',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: true,
    Preview: P.AzkarMorningPreview,
    deepLink: 'rooh-almuslim://azkar/morning',
    androidProvider: 'RoohAzkarSmall',
    legacyAndroidProvider: 'AzkarProgressSmall',
  },
  {
    id: 'azkarEvening',
    category: 'azkar',
    titleAr: 'أذكار المساء',
    titleEn: 'Evening Adhkar',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: true,
    Preview: P.AzkarEveningPreview,
    deepLink: 'rooh-almuslim://azkar/evening',
    androidProvider: 'RoohAzkarSmall',
  },
  {
    id: 'dailyDhikr',
    category: 'azkar',
    titleAr: 'الذكر اليومي',
    titleEn: 'Daily Dhikr',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: true,
    Preview: P.DailyDhikrPreview,
    deepLink: 'rooh-almuslim://daily-dhikr',
    androidProvider: 'RoohAzkarSmall',
    legacyAndroidProvider: 'DailyDhikrSmall',
  },

  // ── Hijri ──────────────────────────────────────────────────────────────────
  {
    id: 'hijriDate',
    category: 'hijri',
    titleAr: 'التاريخ الهجري',
    titleEn: 'Hijri Date',
    sizes: ['small', 'medium'],
    platforms: ['ios', 'android'],
    isPremium: false,
    premiumSizes: ['medium'],
    Preview: P.HijriPreview,
    deepLink: 'rooh-almuslim://hijri',
    androidProvider: 'RoohHijriSmall',
    legacyAndroidProvider: 'HijriDateSmall',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

export function getDefinition(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((d) => d.id === id);
}

export function definitionsForPlatform(platform: WidgetPlatform): WidgetDefinition[] {
  return WIDGET_REGISTRY.filter((d) => d.platforms.includes(platform));
}

/** Widgets visible for a launcher size on a platform (gallery + picker filtering). */
export function definitionsForPlatformAndSize(platform: WidgetPlatform, size: PreviewSize): WidgetDefinition[] {
  return WIDGET_REGISTRY.filter(
    (d) => d.platforms.includes(platform) && d.sizes.includes(size),
  );
}

/** True if this variant requires premium for the given size. */
export function premiumRequiredForSize(def: WidgetDefinition, size: PreviewSize): boolean {
  if (def.premiumSizes && def.premiumSizes.length > 0) return def.premiumSizes.includes(size);
  return !!def.isPremium;
}

export function definitionsByCategory(platform: WidgetPlatform): Record<WidgetCategory, WidgetDefinition[]> {
  const out: Record<WidgetCategory, WidgetDefinition[]> = {
    date: [],
    prayer: [],
    quran: [],
    azkar: [],
    hijri: [],
  };
  for (const d of definitionsForPlatform(platform)) {
    out[d.category].push(d);
  }
  return out;
}

export function legacyAndroidProviders(): string[] {
  const seen = new Set<string>();
  for (const d of WIDGET_REGISTRY) {
    if (d.legacyAndroidProvider) seen.add(d.legacyAndroidProvider);
  }
  return Array.from(seen);
}

export function groupedAndroidProviders(): string[] {
  const seen = new Set<string>();
  for (const d of WIDGET_REGISTRY) {
    if (d.androidProvider) seen.add(d.androidProvider);
  }
  return Array.from(seen);
}

/**
 * Every Android widget provider name known to the app — drawn from
 * `LEGACY_ANDROID_WIDGET_MAP` keys, which now covers both the historic
 * legacy names AND the per-variant names registered in app.json after
 * Phase I. Used by the data-refresh fan-out so that every placement
 * (no matter which provider the user picked from the system widget
 * picker) gets a `requestWidgetUpdate` call.
 */
export function androidWidgetProviderNames(): string[] {
  return [
    ...Object.keys(LEGACY_ANDROID_WIDGET_MAP),
    ...Object.keys(ANDROID_LOCK_WIDGET_MAP),
  ];
}

/**
 * Default PNG route for each react-native-android-widget provider name.
 *
 * Includes:
 *   - The 3 originally-shipped generic providers (RoohSmall/Medium/Large) —
 *     kept so existing user placements continue to render.
 *   - The 11 historic legacy providers (PrayerTimesSmall, …) — kept for users
 *     who placed them when those providers were registered in app.json.
 *   - One provider per (id, size) variant exposed in the gallery on Android
 *     (Phase I: full per-variant picker exposure, mirrors iOS).
 *
 * The variant-specific names follow `Rooh<PascalId><PascalSize>`. The Android
 * launcher's widget picker shows one tile per entry registered in app.json;
 * SnapshotWidget then routes the placement through this map to fetch the
 * correct `<id>_<size>_<theme>.png`.
 */
export const LEGACY_ANDROID_WIDGET_MAP: Record<string, { id: string; size: PreviewSize }> = {
  // Originally-shipped generic providers (still in app.json for backward compat).
  RoohSmall: { id: 'daySimple', size: 'small' },
  RoohMedium: { id: 'daySimple', size: 'medium' },
  RoohLarge: { id: 'prayerTable', size: 'large' },
  // Historic legacy providers — no longer in app.json but mapped for safety.
  PrayerTimesSmall: { id: 'prayerSingle', size: 'small' },
  PrayerTimesMedium: { id: 'prayerSingle', size: 'small' },
  PrayerTimesLarge: { id: 'prayerTable', size: 'large' },
  DailyVerseSmall: { id: 'verseOfDay', size: 'small' },
  DailyVerseMedium: { id: 'verseOfDay', size: 'medium' },
  DailyDhikrSmall: { id: 'dailyDhikr', size: 'small' },
  DailyDhikrMedium: { id: 'dailyDhikr', size: 'medium' },
  AzkarProgressSmall: { id: 'azkarMorning', size: 'small' },
  AzkarProgressMedium: { id: 'azkarMorning', size: 'medium' },
  HijriDateSmall: { id: 'hijriDate', size: 'small' },
  HijriDateMedium: { id: 'hijriDate', size: 'medium' },
  // Phase I — variant-specific providers for the Android picker.
  RoohDaySimpleSmall: { id: 'daySimple', size: 'small' },
  RoohDaySimpleMedium: { id: 'daySimple', size: 'medium' },
  RoohDayThuluthSmall: { id: 'dayThuluth', size: 'small' },
  RoohDayThuluthMedium: { id: 'dayThuluth', size: 'medium' },
  RoohDayDigitalSmall: { id: 'dayDigital', size: 'small' },
  RoohMonthSimpleSmall: { id: 'monthSimple', size: 'small' },
  RoohMonthThuluthMedium: { id: 'monthThuluth', size: 'medium' },
  RoohPrayerSingleSmall: { id: 'prayerSingle', size: 'small' },
  RoohPrayerTableSmall: { id: 'prayerTable', size: 'small' },
  RoohPrayerTableMedium: { id: 'prayerTable', size: 'medium' },
  RoohPrayerTableLarge: { id: 'prayerTable', size: 'large' },
  RoohPrayerNextPreviousMedium: { id: 'prayerNextPrevious', size: 'medium' },
  RoohVerseOfDaySmall: { id: 'verseOfDay', size: 'small' },
  RoohVerseOfDayMedium: { id: 'verseOfDay', size: 'medium' },
  RoohVerseOfDayLarge: { id: 'verseOfDay', size: 'large' },
  RoohAzkarMorningSmall: { id: 'azkarMorning', size: 'small' },
  RoohAzkarMorningMedium: { id: 'azkarMorning', size: 'medium' },
  RoohAzkarEveningSmall: { id: 'azkarEvening', size: 'small' },
  RoohAzkarEveningMedium: { id: 'azkarEvening', size: 'medium' },
  RoohDailyDhikrSmall: { id: 'dailyDhikr', size: 'small' },
  RoohDailyDhikrMedium: { id: 'dailyDhikr', size: 'medium' },
  RoohHijriDateSmall: { id: 'hijriDate', size: 'small' },
  RoohHijriDateMedium: { id: 'hijriDate', size: 'medium' },
};

/**
 * Android keyguard/lock-screen provider names matching the iOS WidgetKit
 * lock-screen widgets in widgets/ios/WidgetBundle.swift. Android lock-screen
 * widget hosting depends on the device/OS widget host, but these provider
 * entries advertise the same content through WIDGET_CATEGORY_KEYGUARD.
 */
export const ANDROID_LOCK_WIDGET_MAP: Record<string, { id: string; size: PreviewSize }> = {
  RoohLockDayThuluth: { id: 'dayThuluth', size: 'small' },
  RoohLockMonthThuluth: { id: 'monthThuluth', size: 'medium' },
  RoohLockNextPrayer: { id: 'prayerSingle', size: 'small' },
  RoohLockAllPrayers: { id: 'prayerTable', size: 'medium' },
  RoohLockHijriCircular: { id: 'hijriDate', size: 'small' },
  RoohLockNextPrayerCountdown: { id: 'prayerSingle', size: 'small' },
};

export function isAndroidLockWidgetProvider(provider: string): boolean {
  return provider in ANDROID_LOCK_WIDGET_MAP;
}

export function androidWidgetProviderTarget(provider: string): { id: string; size: PreviewSize } | null {
  return LEGACY_ANDROID_WIDGET_MAP[provider] ?? ANDROID_LOCK_WIDGET_MAP[provider] ?? null;
}

export function legacyProviderToRegistryLookup(legacy: string): { id: string; size: PreviewSize } | null {
  return androidWidgetProviderTarget(legacy);
}

/**
 * Single source of truth for "is this widget unlocked for the current user".
 */
export function isWidgetUnlocked(def: WidgetDefinition, isPremium: boolean, size: PreviewSize): boolean {
  return !premiumRequiredForSize(def, size) || isPremium;
}

/**
 * Stable, content-aware key for cache invalidation. Bumping
 * WIDGET_REGISTRY_VERSION (see top of file) automatically invalidates every
 * snapshot. Caller should append per-user signature (theme/lang/etc.) — see
 * lib/widgets/snapshot.tsx#computeHash.
 */
export function registryFingerprint(): string {
  const ids = WIDGET_REGISTRY.map((d) => `${d.id}:${d.sizes.join(',')}`).sort().join('|');
  return `v${WIDGET_REGISTRY_VERSION}:${ids}`;
}
