// AUTO-GENERATED by scripts/generate-curated-widget-images.mjs — do not edit by hand.
import Foundation

enum GeneratedCuratedImages {
    static let verseCount = 100
    static let morningCount = 25
    static let eveningCount = 25
    static let dailyCount = 30
}
